added variable cubic-bezier, added sttyles in header
vadimka07/project_team_4 pull request #20
Opened 2021-04-03 12:28 UTC by sergey280680

added variable cubic-bezier, 
added sttyles in header

2021-04-03 13:34 UTC, olozovik requested changes
паддинги в секцию

2021-04-03 13:34 UTC, olozovik commented on src/sass/components/_header.scss
> +  padding-bottom: 30px;
это в секцию

2021-04-03 14:22 UTC, olozovik approved these changes

2021-04-03 18:56 UTC, vadimka07 requested changes
проверь пожалуйста комменты

2021-04-03 18:56 UTC, vadimka07 commented on src/partials/header.html
> +        <ul class="header__list-links">
class="header__list-links", думаю лучше будет header__list-items

2021-04-03 18:56 UTC, vadimka07 commented on src/partials/header.html
> +            <a class="header__link-list" href="#">Программы обучения</a>
а header__link-list лучше заменить на header__item-link

2021-04-03 18:56 UTC, vadimka07 commented on src/partials/header.html
> +            <a class="header__link-list" href="#">О нас</a>
а header__link-list лучше заменить на header__item-link

2021-04-03 18:56 UTC, vadimka07 commented on src/partials/header.html
> +            <a class="header__link-list" href="#">Варианты обучения</a>
а header__link-list лучше заменить на header__item-link

2021-04-03 18:56 UTC, vadimka07 commented on src/partials/header.html
> +            <a class="header__link-list" href="#">Контакты</a>
а header__link-list лучше заменить на header__item-link

2021-04-04 10:16 UTC, vadimka07 approved these changes

2021-04-04 10:16 UTC, merged