добавляет разметку how секции как мы это делаем
vadimka07/project_team_4 pull request #5
Opened 2021-04-01 21:15 UTC by RepetyloYevhenii

Добавил разметку

2021-04-01 23:29 UTC, vadimka07 requested changes
Посмотри комментарий и исправь

2021-04-01 23:29 UTC, vadimka07 commented on src/partials/how.html
> +  <div class="methods__contanier">
<div class="methods__contanier"> переименовать или добавить общий класс container

2021-04-02 07:20 UTC, RepetyloYevhenii commented on src/partials/how.html
> +  <div class="methods__contanier">
Добавил класс

2021-04-02 07:42 UTC, vadimka07 approved these changes, later dismissed

2021-04-02 07:50 UTC, vadimka07 approved these changes

2021-04-02 07:50 UTC, merged