added fonts
vadimka07/project_team_4 pull request #7
Opened 2021-04-01 22:05 UTC by olozovik

Добавил Montserrat 500, 600, 700, 800

2021-04-01 23:36 UTC, vadimka07 requested changes
check message for fonts

2021-04-01 23:36 UTC, vadimka07 commented on src/sass/main.scss
> +@import './utils/fonts';
use this resource https://transfonter.org/ for transform fonts to all format and add local rule

2021-04-02 10:17 UTC, olozovik commented on src/sass/main.scss
> +@import './utils/fonts';
добавил все форматы

2021-04-02 11:53 UTC, vadimka07 requested changes
не все шрифты добавлены и посмотри комментарии

2021-04-02 11:53 UTC, vadimka07 commented on src/sass/utils/_fonts.scss
> +  font-family: 'Montserrat';
font-family: 'Montserrat'; переименовать согласно подключаемого шрифта  font-family:"MontserratExtraBold"

2021-04-02 11:53 UTC, vadimka07 commented on src/sass/utils/_fonts.scss
> +  font-family: 'Montserrat';
font-family: 'Montserrat'; переименовать согласно подключаемого шрифта  font-family:"MontserratBold"

2021-04-02 11:53 UTC, vadimka07 commented on src/sass/utils/_fonts.scss
> +  font-family: 'Montserrat';
font-family: 'Montserrat'; переименовать согласно подключаемого шрифта font-family:"MontserratMedium"

2021-04-02 16:27 UTC, vadimka07 approved these changes
excellent

2021-04-02 16:27 UTC, merged